import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_component/Navbar";
import QueryProvider from "./_providers/QueryProvider";


export const metadata: Metadata = {
  title: "my next js app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" suppressHydrationWarning>
      <body>
        <QueryProvider>
          <div className="min-h-screen bg-black flex flex-col">
            <Navbar />
            <main className="container mx-auto px-4 py-8">
              {children}
            </main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
